#!/usr/bin/env python3
"""
================================================================================
PLOT PPM - Interactive Data Visualization
================================================================================

Generates plots from sensor data collected by the Outer Science Box.
Displays MQ gas sensor readings and BME280 environmental data.

Input:
    data.csv - CSV file generated by serial_logger.py
    
Output:
    Interactive matplotlib windows showing:
    - 2x2 grid: MQ-4 (CH4), MQ-136 (H2S), MQ-8 (H2), MQ-135 (CO2)
    - 1x3 grid: Temperature, Humidity, Pressure

Usage:
    cd /Users/sarforajgazi/outer_science_box/dataplot
    source venv/bin/activate
    python plot_ppm.py

Dependencies:
    pip install pandas matplotlib

CSV Format Expected:
    time_ms,site,sensor,value,unit,temp_C,hum_pct,press_hPa
    123456,1,MQ4_CH4,18.334,ppm,23.95,57.46,1016.12

Author: Team Obseract
================================================================================
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# ==============================================================================
# DATA LOADING
# ==============================================================================

# Get the directory where this script is located
# This ensures the script works regardless of where it's run from
script_dir = os.path.dirname(os.path.abspath(__file__))

# Construct path to data.csv in the same directory as this script
csv_file = os.path.join(script_dir, "data.csv")

# Load CSV data into a pandas DataFrame
# Columns: time_ms, site, sensor, value, unit, temp_C, hum_pct, press_hPa
df = pd.read_csv(csv_file)

# Convert time from milliseconds to seconds for easier reading on plots
df["time_s"] = df["time_ms"] / 1000.0

# ==============================================================================
# INDIVIDUAL SENSOR PLOTTING FUNCTIONS
# ==============================================================================

def plot_sensor(sensor_name, site_id=1):
    """
    Plot a single sensor's data over time.
    
    This function creates a simple line plot for one specific sensor,
    useful for detailed analysis of individual gas concentrations.
    
    Args:
        sensor_name: Name of sensor to plot (e.g., "MQ4_CH4", "MQ136_H2S")
        site_id: Sample site identifier (default: 1)
    
    Example:
        plot_sensor("MQ4_CH4", site_id=1)  # Plot methane data from site 1
    """
    # Filter data for the specified sensor and site
    data = df[(df["sensor"] == sensor_name) & (df["site"] == site_id)]

    # Check if any data exists
    if data.empty:
        print(f"No data for {sensor_name} at site {site_id}")
        return

    # Create the plot
    plt.figure()
    plt.plot(data["time_s"], data["value"])
    plt.xlabel("Time (s)")
    plt.ylabel(f"{sensor_name} ({data['unit'].iloc[0]})")
    plt.title(f"{sensor_name} vs Time (Site {site_id})")
    plt.grid(True)
    plt.show()


def plot_environment(param, site_id=1):
    """
    Plot a single environmental parameter over time.
    
    Args:
        param: Parameter name (column in DataFrame)
        site_id: Sample site identifier (default: 1)
    
    Example:
        plot_environment("temp_C", site_id=1)  # Plot temperature
    """
    # Filter data for the specified site
    data = df[df["site"] == site_id]

    # Create the plot
    plt.figure()
    plt.plot(data["time_s"], data[param])
    plt.xlabel("Time (s)")
    plt.ylabel(param)
    plt.title(f"{param} vs Time (Site {site_id})")
    plt.grid(True)
    plt.show()


# ==============================================================================
# INDIVIDUAL SENSOR PLOTS (Uncomment to use)
# ==============================================================================
# These can be used for detailed analysis of specific sensors
# Uncomment the lines below to plot individual sensors:
#
# plot_sensor("MQ4_CH4", site_id=1)     # Methane
# plot_sensor("MQ136_H2S", site_id=1)   # Hydrogen Sulfide
# plot_sensor("MQ8_H2", site_id=1)      # Hydrogen
# plot_sensor("MQ135_CO2", site_id=1)   # Carbon Dioxide


# ==============================================================================
# COMBINED MQ SENSOR PLOT (2x2 Grid)
# ==============================================================================

def plot_all_sensors_combined(site_id=1):
    """
    Plot all 4 MQ gas sensors in a 2x2 grid layout.
    
    This is the primary visualization for gas sensor data.
    Each subplot shows one sensor's concentration over time.
    
    Layout:
        ┌─────────────────┬─────────────────┐
        │ MQ-4 Methane    │ MQ-136 H2S      │
        ├─────────────────┼─────────────────┤
        │ MQ-8 Hydrogen   │ MQ-135 CO2      │
        └─────────────────┴─────────────────┘
    
    Args:
        site_id: Sample site identifier (default: 1)
    """
    # Sensor configuration: (csv_name, display_title, color)
    sensors = [
        ("MQ4_CH4",   "MQ-4 Methane (CH₄)",   "tab:blue"),    # Top-left
        ("MQ136_H2S", "MQ-136 H₂S",           "tab:orange"),  # Top-right
        ("MQ8_H2",    "MQ-8 Hydrogen (H₂)",   "tab:green"),   # Bottom-left
        ("MQ135_CO2", "MQ-135 CO₂",           "tab:red")      # Bottom-right
    ]
    
    # Create 2x2 subplot grid
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()  # Convert 2D array to 1D for easier iteration
    
    # Plot each sensor
    for ax, (sensor_name, title, color) in zip(axes, sensors):
        # Filter data for this sensor and site
        data = df[(df["sensor"] == sensor_name) & (df["site"] == site_id)]
        
        # Handle case where sensor has no data
        if data.empty:
            ax.set_title(f"{title}\n(No Data)")
            ax.axis("off")  # Hide axes for empty plots
            continue
        
        # Plot the data
        ax.plot(data["time_s"], data["value"], color=color, linewidth=1.5)
        ax.set_title(title, fontsize=12)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(f"{data['unit'].iloc[0]}")  # Get unit from first row
        ax.grid(True, alpha=0.3)  # Light grid lines
    
    # Add main title
    plt.suptitle("MQ Gas Sensors — Team Obseract Rover", fontsize=16)
    
    # Adjust layout to prevent overlap
    # rect=[left, bottom, right, top] leaves space for suptitle
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    
    # Display the plot
    plt.show()


# ==============================================================================
# COMBINED ENVIRONMENT PLOT (1x3 Grid)
# ==============================================================================

def plot_all_env_combined(site_id=1):
    """
    Plot all BME280 environmental data in a 1x3 grid layout.
    
    Shows temperature, humidity, and pressure from the BME280 sensor.
    
    Layout:
        ┌─────────────┬─────────────┬─────────────┐
        │ Temperature │  Humidity   │  Pressure   │
        └─────────────┴─────────────┴─────────────┘
    
    Args:
        site_id: Sample site identifier (default: 1)
    """
    # Environment parameter configuration: (csv_name, display_title, unit, color)
    env_params = [
        ("BME_TEMP",  "Temperature", "°C",  "tab:red"),
        ("BME_HUM",   "Humidity",    "%",   "tab:blue"),
        ("BME_PRESS", "Pressure",    "hPa", "tab:green")
    ]
    
    # Create 1x3 subplot grid (wide format)
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    
    # Plot each environmental parameter
    for ax, (sensor_name, title, unit, color) in zip(axes, env_params):
        # Filter data for this parameter and site
        data = df[(df["sensor"] == sensor_name) & (df["site"] == site_id)]
        
        # Handle case where no data exists
        if data.empty:
            ax.set_title(f"{title}\n(No Data)")
            continue
        
        # Plot the data
        ax.plot(data["time_s"], data["value"], color=color, linewidth=1.5)
        ax.set_title(title, fontsize=12)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(unit)
        ax.grid(True, alpha=0.3)  # Light grid lines
    
    # Add main title
    plt.suptitle("BME280 Environmental Data — Team Obseract Rover", fontsize=14)
    
    # Adjust layout
    plt.tight_layout(rect=[0, 0, 1, 0.92])
    
    # Display the plot
    plt.show()


# ==============================================================================
# MAIN EXECUTION
# ==============================================================================
# When this script is run directly, generate both combined plots

if __name__ == "__main__":
    print("Generating MQ sensor plot (2x2 grid)...")
    plot_all_sensors_combined(site_id=1)
    
    print("Generating BME280 environmental plot (1x3 grid)...")
    plot_all_env_combined(site_id=1)
    
    print("Done!")
